import Head from "next/head";
import "../styles/style.scss";
<<<<<<< HEAD
import '../styles/layout/style.css'
import "bootstrap/dist/css/bootstrap.css"

=======
import '../styles/layout/style.css';
import "bootstrap/dist/css/bootstrap.css";
>>>>>>> 942996b2b5c6b72af0014d5714d082acc6fbdd44

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Pertamini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Component {...pageProps} />
    </>
  );
}

export default MyApp;
